project_id = "ehalcuqxjpdykpmjxxrn"

[functions.oscar-chat]
verify_jwt = false

[functions.send-family-notification]
verify_jwt = false

[functions.check-document-reminders]
verify_jwt = false

[functions.analyze-scam]

[functions.fetch-scam-alerts]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.custom-sms-hook]
verify_jwt = false
